"""add color project

Revision ID: 36ea5bf013aa
Revises: a618b978eae4
Create Date: 2025-07-16 18:33:11.477734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ea5bf013aa'
down_revision: Union[str, Sequence[str], None] = 'a618b978eae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Добавляем столбец color как nullable
    op.add_column('projects', sa.Column(
        'color', sa.String(length=16), nullable=True))
    # 2. Заполняем существующие строки дефолтным цветом
    op.execute("UPDATE projects SET color = '#1f77b4' WHERE color IS NULL")
    # 3. Делаем столбец NOT NULL
    op.alter_column('projects', 'color', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'color')
    # ### end Alembic commands ###
