"""add color to user

Revision ID: 7cbb8bee38e8
Revises: 36ea5bf013aa
Create Date: 2025-07-16 19:13:50.513875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbb8bee38e8'
down_revision: Union[str, Sequence[str], None] = '36ea5bf013aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем столбец color как nullable
    op.add_column('users', sa.Column('color', sa.String(length=16), nullable=True))
    # 2. Заполняем существующие строки дефолтным цветом
    op.execute("UPDATE users SET color = '#ff7f0e' WHERE color IS NULL")
    # 3. Делаем столбец NOT NULL
    op.alter_column('users', 'color', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'color')
    # ### end Alembic commands ###
