"""Add project access control

Revision ID: cb0ed12a31ce
Revises: e3a82b577e7f
Create Date: 2025-06-22 13:15:20.950983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0ed12a31ce'
down_revision: Union[str, Sequence[str], None] = 'e3a82b577e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project_access',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('granted_by_id', sa.UUID(), nullable=True),
                    sa.Column('granted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'project_id')
                    )
    op.add_column('projects', sa.Column(
        'description', sa.String(), nullable=True))

    # Добавляем is_public как nullable, затем заполняем значениями и делаем NOT NULL
    op.add_column('projects', sa.Column(
        'is_public', sa.Boolean(), nullable=True))
    op.execute("UPDATE projects SET is_public = false")
    op.alter_column('projects', 'is_public', nullable=False)

    # Добавляем поля в users как nullable, затем заполняем и делаем NOT NULL
    op.add_column('users', sa.Column(
        'can_load_tasks', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column(
        'can_view_reports', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET can_load_tasks = false, can_view_reports = false")
    op.alter_column('users', 'can_load_tasks', nullable=False)
    op.alter_column('users', 'can_view_reports', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_view_reports')
    op.drop_column('users', 'can_load_tasks')
    op.drop_column('projects', 'is_public')
    op.drop_column('projects', 'description')
    op.drop_table('user_project_access')
    # ### end Alembic commands ###
